version: '3.3'

services:
   wordpress:
     image: wordpress:latest
     container_name: wordpress
     ports:
       - "8000:80"
     restart: always
     volumes:
      - ./volumes/project:/var/www/html
     networks:
      - abel-network
     environment:
       WORDPRESS_DB_HOST: mysql5:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD:
       WORDPRESS_DB_NAME: wordpress


networks:
  abel-network:
    external: true


